services:
  go-whatsapp:
    image: aldinokemal2104/go-whatsapp-web-multidevice
    container_name: go-whatsapp
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - gowa-whatsapp:/app/storages
    command:
      - rest
    env_file:
      - ../.env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M

  gowabot:
    image: gowabot
    container_name: gowabot
    restart: always
    ports:
      - "127.0.0.1:5000:5000"
    env_file:
      - ../.env
    depends_on:
      - go-whatsapp
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M

volumes:
  gowa-whatsapp: